import { embed } from '@aws/dynamodb-data-mapper';
import {
  table,
  attribute,
  autoGeneratedHashKey,
  rangeKey
} from '@aws/dynamodb-data-mapper-annotations';
import { PORTFOLIOS_TABLE } from '../config';

interface TableIndexes {
  pk: string;
  sk: string;
  data: string;
}

@table(PORTFOLIOS_TABLE)
export class Portfolio implements TableIndexes {
  @autoGeneratedHashKey()
  pk: string;

  @rangeKey()
  sk: string;

  @attribute()
  data: string;

  @attribute()
  name?: string;

  @attribute()
  postedAt?: Date;

  @attribute()
  currency?: string;
}
